'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class asset
    Public Property asset_id As Integer
    Public Property model As String
    Public Property po_number As String
    Public Property manufacture As String
    Public Property serial_number As String
    Public Property description As String
    Public Property warranty_date As Date
    Public Property status_id As Integer
    Public Property order_id As Integer
    Public Property asset_type_id As Integer

    Public Overridable Property asset1 As asset
    Public Overridable Property asset2 As asset
    Public Overridable Property order As order
    Public Overridable Property status As status
    Public Overridable Property assigns As ICollection(Of assign) = New HashSet(Of assign)
    Public Overridable Property locations As ICollection(Of location) = New HashSet(Of location)
    Public Overridable Property return_asset As ICollection(Of return_asset) = New HashSet(Of return_asset)
    Public Overridable Property technical_room As ICollection(Of technical_room) = New HashSet(Of technical_room)

End Class
