'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class asset_type
    Public Property type_id As Integer
    Public Property asset_type1 As String

    Public Overridable Property return_asset As ICollection(Of return_asset) = New HashSet(Of return_asset)

End Class
