'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel

Partial Public Class item
    <DisplayName("Item ID")>
    Public Property item_id As Integer
    <DisplayName("Item Name")>
    Public Property item_name As String
    <DisplayName("Description")>
    Public Property description As String
    <DisplayName("Quantity")>
    Public Property quantity As Integer
    <DisplayName("Manufacturer")>
    Public Property manufacture As String
    Public Property order_id As Nullable(Of Integer)

    Public Overridable Property order As order

End Class
