'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class item
    Public Property item_id As Integer
    Public Property item_name As String
    Public Property description As String
    Public Property quantity As Integer
    Public Property manufacture As String
    Public Property order_id As Nullable(Of Integer)

    Public Overridable Property order As order

End Class
