'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class location
    Public Property location_id As Integer
    Public Property serial_number As String
    Public Property location1 As String
    Public Property asset_id As Integer

    Public Overridable Property asset As asset

End Class
