'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class itamDB
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=itamDB")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property assets() As DbSet(Of asset)
    Public Overridable Property asset_type() As DbSet(Of asset_type)
    Public Overridable Property assigns() As DbSet(Of assign)
    Public Overridable Property items() As DbSet(Of item)
    Public Overridable Property locations() As DbSet(Of location)
    Public Overridable Property notifications() As DbSet(Of notification)
    Public Overridable Property orders() As DbSet(Of order)
    Public Overridable Property requesters() As DbSet(Of requester)
    Public Overridable Property status() As DbSet(Of status)
    Public Overridable Property stocks() As DbSet(Of stock)
    Public Overridable Property technical_room() As DbSet(Of technical_room)
    Public Overridable Property technicians() As DbSet(Of technician)
    Public Overridable Property trials() As DbSet(Of trial)
    Public Overridable Property return_asset() As DbSet(Of return_asset)

End Class
