'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class order
    Public Property order_id As Integer
    Public Property order_number As String
    Public Property order_date As Nullable(Of Date)
    Public Property eta As Nullable(Of Date)
    Public Property invoice_number As String

    Public Overridable Property assets As ICollection(Of asset) = New HashSet(Of asset)
    Public Overridable Property items As ICollection(Of item) = New HashSet(Of item)
    Public Overridable Property stocks As ICollection(Of stock) = New HashSet(Of stock)

End Class
