'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class return_asset
    Public Property return_id As Integer
    Public Property serial_number As String
    Public Property return_date As Date
    Public Property manufacture As String
    Public Property warranty_date As Date
    Public Property report As String
    Public Property asset_id As Integer
    Public Property asset_type_id As Integer
    Public Property status_id As Integer

    Public Overridable Property asset As asset
    Public Overridable Property asset_type As asset_type
    Public Overridable Property status As status

End Class
