'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class status
    Public Property status_id As Integer
    Public Property status_name As String
    Public Property description As String

    Public Overridable Property assets As ICollection(Of asset) = New HashSet(Of asset)
    Public Overridable Property assigns As ICollection(Of assign) = New HashSet(Of assign)
    Public Overridable Property return_asset As ICollection(Of return_asset) = New HashSet(Of return_asset)
    Public Overridable Property stocks As ICollection(Of stock) = New HashSet(Of stock)
    Public Overridable Property technical_room As ICollection(Of technical_room) = New HashSet(Of technical_room)

End Class
