'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class stock
    Public Property stock_id As Integer
    Public Property quantity As String
    Public Property model As String
    Public Property order_id As Integer
    Public Property status_id As Integer

    Public Overridable Property order As order
    Public Overridable Property status As status

End Class
