'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class technical_room
    Public Property technical_id As Integer
    Public Property upload_icf As String
    Public Property status_id As Integer
    Public Property asset_id As Integer
    Public Property technician_id As Integer

    Public Overridable Property asset As asset
    Public Overridable Property status As status
    Public Overridable Property technician As technician

End Class
