'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class trial
    Public Property order_stock As Integer
    Public Property model1 As String
    Public Property model2 As String
    Public Property model3 As String
    Public Property quantity1 As String
    Public Property quantity2 As String
    Public Property quantity3 As String
    Public Property invoice_number As String
    Public Property [date] As Nullable(Of Date)
    Public Property description As String
    Public Property eta As String

End Class
